### PR TITLE
Add actual beans.xml file

### PR DESCRIPTION
**Pull request by aslakknutsen**

### CODE REVIEW

**Comment by rmpestano** [comment]
Thank you @aslakknutsen for your tips, still got null bm (even for in container) but now I have the direction,

**Comment by rmpestano** [comment]
Owww I see a green bar here! 

thought it had failled because I was debuging in the IDE (which was in the client).

Thank you very much!

**Comment by aslakknutsen** [comment]
really? EnableCDI pass for me

**Comment by aslakknutsen** [comment]
oh, there you go ! :+1:

**Pull request merged**
